//go:build flutterui

// SPDX-License-Identifier: AGPL-3.0-or-later
package panel

import (
	"embed"
	"io/fs"
	"net/http"
)

// Generated by scripts/build-ui.sh web before compiling the release backend.
// No placeholder UI is shipped when the web build has not been staged.
//
//go:embed all:flutter
var flutterAssets embed.FS

func Application(api http.Handler) http.Handler {
	assets, err := fs.Sub(flutterAssets, "flutter")
	if err != nil {
		panic(err)
	}
	if _, err := fs.Stat(assets, "index.html"); err != nil {
		panic("build Flutter assets before compiling Caspian")
	}
	return applicationWithAssets(api, assets)
}
