// SPDX-License-Identifier: AGPL-3.0-or-later

package hotspot

import (
	"flag"
	"os"
	"path/filepath"
	"testing"
)

// WHAT A GOLDEN FILE HERE DOES AND DOES NOT PROVE.
//
// A golden proves the generated bytes have not changed without somebody
// looking at the diff. It does not prove the program that consumes them still
// accepts them. Those are different claims, and in this package the two
// configurations stand in very different places on the second one:
//
//   - dnsmasq CAN be checked cheaply and often. "dnsmasq --test --conf-file=X"
//     parses and exits. TestGoldenDnsmasqConfigIsAcceptedByDnsmasq in
//     external_test.go runs it against the committed file, and was measured
//     accepting it on the target Pi on 2026-08-30 (dnsmasq 2.91).
//
//   - hostapd CANNOT. There is no validate-and-exit flag. The full option set
//     of hostapd 2.10 was read off the box on 2026-08-30: h, d, B, K, t, v, P,
//     e, g, G, f, T, i, S, and none of them checks a configuration without
//     starting it. In particular -t is NOT a test flag: it means "include
//     timestamps in some debug messages", and anyone reaching for it as a
//     syntax check gets a running access point instead.
//
// So the only way to prove a hostapd configuration is to run it, which takes
// the radio, which means a real bring-up on hardware. That is a property of
// hostapd, not a gap in this package, and it will not be closed by trying
// harder.
//
// THE CONSEQUENCE, STATED SO NOBODY ASSUMES SYMMETRY: after a green test run
// on a developer machine, the dnsmasq configuration has been checked by
// dnsmasq if dnsmasq was installed, and the hostapd configuration has been
// checked by NOTHING except this package's own assertions about its own
// output. hostapd.golden is a change detector and only a change detector until
// a bring-up on hardware says otherwise.

// -update rewrites the golden files. Run it, then READ THE DIFF: the point of
// a golden file is that a change to what this appliance broadcasts, or to what
// it logs, cannot land without a human looking at it.
var update = flag.Bool("update", false, "rewrite the golden files in testdata")

func assertGolden(t *testing.T, name, got string) {
	t.Helper()
	path := filepath.Join("testdata", name)

	if *update {
		if err := os.WriteFile(path, []byte(got), 0o644); err != nil {
			t.Fatalf("could not write golden %s: %v", path, err)
		}
		t.Logf("wrote %s", path)
		return
	}

	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("could not read golden %s: %v (run: go test ./internal/hotspot -update)", path, err)
	}
	if got != string(want) {
		t.Errorf("generated configuration does not match %s\n--- want ---\n%s\n--- got ---\n%s",
			path, want, got)
	}
}

// testAP is the reference access point used by the golden test and by most of
// the others. Channel 10 is not arbitrary: it is the channel the Raspberry Pi 5
// in docs/2026-08-29-design.md section 4.6 was measured holding on its client
// link, and the built-in radio reports "#channels <= 1", so it is also the only
// channel the access point could use on that box.
func testAP() APConfig {
	return APConfig{
		Interface:   "wlan0",
		SSID:        "Caspian",
		Passphrase:  "correct-horse-battery",
		CountryCode: "GB",
		Channel:     10,
		Band:        Band2GHz,
		ControlDir:  "/run/hostapd",
	}
}
