// SPDX-License-Identifier: AGPL-3.0-or-later

package hotspot

import (
	"fmt"
	"strings"
)

// RenderHostapd turns a validated APConfig into a hostapd configuration file.
//
// Pure: no files, no processes, no network. The output is fixed by
// testdata/hostapd.golden so any change to what this appliance broadcasts
// appears as a diff in review.
//
// Several settings here exist because the reference implementation this
// replaces got them wrong. Each of those carries the failure by name.
func RenderHostapd(cfg APConfig) (string, error) {
	if err := cfg.Validate(); err != nil {
		return "", err
	}
	mode, err := cfg.hwMode()
	if err != nil {
		return "", err
	}
	ctrlDir := cfg.ControlDir
	if ctrlDir == "" {
		ctrlDir = DefaultPaths().HostapdControlDir
	}

	var b strings.Builder
	p := func(format string, args ...any) {
		fmt.Fprintf(&b, format+"\n", args...)
	}

	p("# hostapd configuration generated by Caspian-BYOC.")
	p("# Rewritten from scratch on every start. Edits here are lost.")
	p("#")
	p("# Every setting below is here for a reason and the reason is written down.")
	p("# Where a setting exists because of a known failure, the failure is named.")
	p("")
	p("interface=%s", cfg.Interface)
	p("driver=nl80211")
	p("")
	p("# The regulatory domain.")
	p("#")
	p("# WHY THIS LINE IS FIRST AMONG EQUALS: with no country_code the driver")
	p("# uses the world regulatory domain, in which most channels are")
	p("# passive-scan only and beaconing is not permitted, so hostapd starts,")
	p("# fails to bring the interface up and the network never appears. The")
	p("# user sees nothing at all, which is the least diagnosable failure this")
	p("# appliance can produce. The reference implementation omitted it")
	p("# entirely: 004-hotspot/install.sh:415-430 writes no country_code line.")
	p("#")
	p("# ieee80211d advertises the domain in the beacon so joining clients")
	p("# adopt the same channel and power rules.")
	p("country_code=%s", cfg.CountryCode)
	p("ieee80211d=1")
	p("")
	p("# The network name. utf8_ssid tells hostapd the bytes are UTF-8, which")
	p("# matters because this appliance's users name their networks in scripts")
	p("# other than Latin and a name advertised in the wrong encoding shows up")
	p("# on phones as replacement characters.")
	p("ssid=%s", cfg.SSID)
	p("utf8_ssid=1")
	p("")
	p("hw_mode=%s", mode)
	p("channel=%d", cfg.Channel)
	p("")
	p("# 802.11n.")
	p("#")
	p("# Without ieee80211n the radio negotiates 802.11g rates only and the")
	p("# whole hotspot is capped at 54 Mbps shared between every joined device,")
	p("# below what the tunnel can carry. The reference implementation set")
	p("# neither ieee80211n nor wmm_enabled=1 (004-hotspot/install.sh:415-430,")
	p("# which has wmm_enabled=0), so every box it built ran at 54 Mbps and")
	p("# nothing said so.")
	p("#")
	p("# wmm_enabled=1 is not optional here: hostapd disables HT rates when WMM")
	p("# is off, so ieee80211n=1 with wmm_enabled=0 silently stays at 54 Mbps")
	p("# and looks configured.")
	p("ieee80211n=1")
	p("wmm_enabled=1")
	p("")
	p("# 20 MHz channel width only.")
	p("#")
	p("# HT40 needs a secondary channel declared as [HT40+] or [HT40-], and the")
	p("# correct one depends on the primary channel and the regulatory domain.")
	p("# A wrong secondary makes hostapd refuse to start. This appliance is")
	p("# frequently pinned to whatever channel the uplink already uses (see")
	p("# RadioConstraint), so the primary is not ours to choose and the safe")
	p("# gain is the short guard interval at 20 MHz.")
	p("ht_capab=[SHORT-GI-20]")
	p("")
	p("# Security: WPA2-PSK with CCMP (AES) and nothing else.")
	p("#")
	p("# auth_algs=1 is Open System only. The value 2 enables WEP shared-key")
	p("# authentication, which is broken.")
	p("#")
	p("# There is deliberately NO wpa_pairwise line. wpa_pairwise sets the")
	p("# cipher for WPA1, and the reference implementation set")
	p("# wpa_pairwise=TKIP (004-hotspot/install.sh:428). That has two costs,")
	p("# not one: it advertises a cipher with known practical attacks, and")
	p("# because 802.11n forbids HT rates on a BSS that offers TKIP it also")
	p("# holds the whole network at 54 Mbps however much 802.11n is enabled")
	p("# above. Omitting the line leaves rsn_pairwise as the only cipher suite,")
	p("# which is WPA2 with AES.")
	p("auth_algs=1")
	p("wpa=2")
	p("wpa_key_mgmt=WPA-PSK")
	p("rsn_pairwise=CCMP")
	p("wpa_passphrase=%s", cfg.Passphrase)
	p("")
	p("# Devices that join must not be able to reach each other.")
	p("#")
	p("# Everyone here is a guest of whoever holds the passphrase, and a phone")
	p("# joining a shared hotspot should not be exposed to the other phones on")
	p("# it. ap_isolate stops hostapd bridging frames from one associated")
	p("# station to another. It is not the whole of client isolation: traffic")
	p("# that leaves the interface and comes back is internal/netcfg's firewall")
	p("# to stop, and this line does not claim to do that job.")
	p("ap_isolate=1")
	p("")
	p("# No MAC filtering, and the name is broadcast. A hidden SSID is not")
	p("# security, it only stops the user finding their own network.")
	p("macaddr_acl=0")
	p("ignore_broadcast_ssid=0")
	p("")
	p("# Logging: notification level and above.")
	p("#")
	p("# hostapd writes a line for every association and disassociation, each")
	p("# carrying a device's MAC address, at informational level. This box does")
	p("# not keep a record of which devices were here. Errors stay visible so")
	p("# the panel can explain a failure.")
	p("logger_syslog=-1")
	p("logger_syslog_level=3")
	p("logger_stdout=-1")
	p("logger_stdout_level=3")
	p("")
	p("# Control socket. Used only by this program, to ask hostapd whether the")
	p("# access point is actually up rather than merely running: a hostapd")
	p("# process that is alive and beaconing nothing is the failure a process")
	p("# check cannot see.")
	p("ctrl_interface=%s", ctrlDir)
	p("ctrl_interface_group=0")

	return b.String(), nil
}
