package goldenscan

import (
	"encoding/xml"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// The four language editions of the level-0 flow diagram, generated by
// scripts/make-flow-diagram.py and embedded at the top of each README.
var flowDiagrams = []string{
	"docs/images/flow-en.svg",
	"docs/images/flow-fa.svg",
	"docs/images/flow-ru.svg",
	"docs/images/flow-zh.svg",
}

// TestTheFlowDiagramsFetchNothing holds the diagram to the same rule as the
// panel: it asks the internet for nothing.
//
// An SVG can carry a <script>, pull a font over @import, or embed a remote
// <image>. Any of those turns opening the README into a request to a third
// party, which tells that party the address of everyone who reads about a
// censorship-circumvention tool. That is a worse leak than anything the diagram
// explains, and it would arrive by way of a picture nobody thinks to audit.
//
// This checks the shipped bytes rather than the generator, because the shipped
// bytes are what a reader loads.
func TestTheFlowDiagramsFetchNothing(t *testing.T) {
	root := moduleRoot(t)

	// Any scheme-bearing or protocol-relative reference. The SVG and xlink
	// namespace URIs are declarations rather than fetches, so they are the only
	// permitted occurrences and are stripped before this runs.
	remote := regexp.MustCompile(`(?i)(https?:)?//`)
	banned := []string{"<script", "<foreignObject", "<image", "@import", "xlink:href", "href=", "src="}

	for _, rel := range flowDiagrams {
		body, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Errorf("%s: %v\nRegenerate with: python3 scripts/make-flow-diagram.py", rel, err)
			continue
		}
		text := string(body)

		if err := xml.Unmarshal(body, new(struct {
			XMLName xml.Name
		})); err != nil {
			t.Errorf("%s is not well-formed XML: %v", rel, err)
		}

		for _, b := range banned {
			if strings.Contains(strings.ToLower(text), strings.ToLower(b)) {
				t.Errorf("%s contains %q. The diagram must be self-contained: no script, "+
					"no remote font, no remote image. Opening the README should not tell "+
					"anybody that you opened it.", rel, b)
			}
		}

		stripped := strings.ReplaceAll(text, "http://www.w3.org/2000/svg", "")
		if m := remote.FindString(stripped); m != "" {
			t.Errorf("%s carries what looks like a remote reference (%q). Everything the "+
				"diagram needs is drawn in the file.", rel, m)
		}
	}
}

// TestTheFlowDiagramNamesOnlyProtocolsTheParserAccepts ties the picture to the
// code.
//
// The diagram is the first thing on the page and the last thing anybody
// re-reads, so a protocol drawn on it is believed long after it stops working.
// A picture is not read as a claim that could be checked, which is exactly why
// it needs checking mechanically.
//
// So the accepted set is read out of internal/link's own source rather than
// restated here. Removing a scheme from supportedSchemes fails this test until
// the diagram is regenerated.
func TestTheFlowDiagramNamesOnlyProtocolsTheParserAccepts(t *testing.T) {
	root := moduleRoot(t)

	src, err := os.ReadFile(filepath.Join(root, "internal", "link", "link.go"))
	if err != nil {
		t.Fatalf("reading internal/link/link.go: %v", err)
	}
	block := regexp.MustCompile(`(?s)supportedSchemes\s*=\s*map\[string\]bool\{(.*?)\n\}`).FindSubmatch(src)
	if block == nil {
		t.Fatal("could not find supportedSchemes in internal/link/link.go. If it was " +
			"renamed, update this test rather than deleting it: the point is that the " +
			"diagram cannot name a protocol the parser has stopped accepting.")
	}
	accepted := map[string]bool{}
	for _, m := range regexp.MustCompile(`"([a-z0-9+]+)"\s*:\s*true`).FindAllSubmatch(block[1], -1) {
		accepted[string(m[1])] = true
	}
	if len(accepted) < 5 {
		t.Fatalf("only parsed %d schemes out of supportedSchemes, which cannot be right", len(accepted))
	}

	// How a name on the diagram maps to the scheme the parser matches on.
	drawn := map[string]string{
		"VLESS":       "vless",
		"VMess":       "vmess",
		"Trojan":      "trojan",
		"Shadowsocks": "ss",
		"SOCKS":       "socks",
		"Hysteria2":   "hysteria2",
	}

	body, err := os.ReadFile(filepath.Join(root, flowDiagrams[0]))
	if err != nil {
		t.Fatalf("reading %s: %v", flowDiagrams[0], err)
	}
	text := string(body)

	var named []string
	for label, scheme := range drawn {
		if !strings.Contains(text, label) {
			continue
		}
		named = append(named, label)
		if !accepted[scheme] {
			t.Errorf("the diagram names %s, but %q is not in internal/link's "+
				"supportedSchemes. Either the parser stopped accepting it, in which case "+
				"regenerate the diagram, or the label is wrong.", label, scheme)
		}
	}
	sort.Strings(named)
	// Every label in the table must appear. A floor lower than the table size
	// lets a typo through: renaming Hysteria2 to Hysteria9 in the SVG left five
	// correct labels and passed a floor of five, which is a guard that reports
	// the diagram is fine while it names a protocol that does not exist.
	if len(named) != len(drawn) {
		var absent []string
		for label := range drawn {
			if !strings.Contains(text, label) {
				absent = append(absent, label)
			}
		}
		sort.Strings(absent)
		t.Errorf("the diagram names %d of the %d protocols this test knows about; "+
			"missing or misspelt: %s.\nIf a protocol was deliberately dropped from the "+
			"picture, drop it from the table in this test too, so the next reader knows "+
			"which is authoritative.", len(named), len(drawn), strings.Join(absent, ", "))
	}

	// Every language edition names the same protocols. The strip is generated
	// from one constant, so a mismatch means a file was hand-edited.
	for _, rel := range flowDiagrams[1:] {
		other, err := os.ReadFile(filepath.Join(root, rel))
		if err != nil {
			t.Errorf("reading %s: %v", rel, err)
			continue
		}
		for _, label := range named {
			if !strings.Contains(string(other), label) {
				t.Errorf("%s does not name %s though the English edition does. The four "+
					"diagrams come from one generator; regenerate rather than editing "+
					"an SVG by hand.", rel, label)
			}
		}
	}
}
